spring.datasource.url=jdbc:postgresql://localhost:5432/studydb
spring.datasource.username=postgres
spring.datasource.password=shamita@3371

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect